language: node_js
node_js:
  - '10'

cache:
  directories:
    - 'node_modules'

branches:
  only:
    - master

install:
  - yarn install
  - DEPLOY_ENV=GH_PAGES yarn run generate

script:
  - echo "Skipping tests"

before_deploy:
  # Github Pageではルートディレクトリアクセス時index.htmlよりもREADME.mdが優先されるので退避
  - mkdir dist/.github
  - mv dist/README.md dist/.github
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_ACCESS_TOKEN
  target-branch: gh-pages
  local-dir: dist
  on:
    branch: master
